"""
Django settings for Nexus project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _ # <<< Import for lazy translation
import dj_database_url
from decimal import Decimal # For PLATFORM_COMMISSION_RATE
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'japz1)gr54xbt=6x5870ti&+r$_h#mdo7nepbl2*nen12()tev')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production. The '0' == '1' pattern is a common way to handle boolean env vars.
DEBUG = os.environ.get('DEBUG', '1') == '1'

ALLOWED_HOSTS = [
    '127.0.0.1', 'localhost', 'gowbuy-project.onrender.com',
    'gowbuy.com', 'www.gowbuy.com',
    'gowbuy.co.uk', 'www.gowbuy.co.uk',
    '.ngrok-free.app', # Allow ngrok free domains
    '.ngrok.io',       # Allow older ngrok domains
    '.ngrok-free.dev', # Allow ngrok dev domains
]
CSRF_TRUSTED_ORIGINS = [
    'https://gowbuy-project.onrender.com',
    'https://gowbuy.com', 'https://www.gowbuy.com',
    'https://gowbuy.co.uk', 'https://www.gowbuy.co.uk',
    'https://*.ngrok-free.app', # Allow ngrok free domains
    'https://*.ngrok.io',       # Allow older ngrok domains
    'https://*.ngrok-free.dev', # Allow ngrok dev domains
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

# settings.py

INSTALLED_APPS = [
    # ... your apps first (optional, but common)
    'jazzmin', # Moved to top as per documentation
    'core.apps.CoreConfig',
    'authapp.apps.AuthappConfig',
    'channels',


    # Django contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'django.contrib.humanize',
    'django.contrib.sites',  # <<< Add the sites framework
    'django.contrib.sitemaps', # Add sitemaps app

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    'paypal.standard.ipn',
    'modeltranslation',  # <<< Add modeltranslation for database field translation
    'tinymce',
    'django_bleach',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.mfa', # Ensure this line is present
    # 'allauth.socialaccount',
    'django_ratelimit',  # <-- Add this line
    
    # Specific provider apps:
    #  'allauth.socialaccount.providers.google',
    #  'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.apple', # Removed Apple
]

# TinyMCE configuration
TINYMCE_JS_URL = 'https://cdn.jsdelivr.net/npm/tinymce@6/tinymce.min.js'  # Use jsDelivr CDN (no API key required)
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview anchor '
               'searchreplace visualblocks code fullscreen insertdatetime media table '
               'paste code help wordcount',
    'toolbar': 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | '
               'alignleft aligncenter alignright alignjustify | outdent indent | '
               'numlist bullist | forecolor backcolor removeformat | pagebreak | '
               'charmap emoticons | fullscreen preview save print | insertfile image media template link anchor codesample | '
               'ltr rtl',
    'custom_undo_redo_levels': 10,
}

# Bleach (HTML sanitization) configuration
BLEACH_ALLOWED_TAGS = ['p', 'b', 'i', 'u', 'em', 'strong', 'a', 'ul', 'ol', 'li', 'br', 'h1', 'h2', 'h3']
BLEACH_ALLOWED_ATTRIBUTES = {'a': ['href', 'title']}
BLEACH_STRIP_TAGS = True
BLEACH_STRIP_COMMENTS = True

# PayPal settings
PAYPAL_TEST = not (os.environ.get('PAYPAL_LIVE_MODE', 'False') == 'True') # False in production if PAYPAL_LIVE_MODE is 'True'
PAYPAL_RECEIVER_EMAIL = os.environ.get('PAYPAL_RECEIVER_EMAIL')

SITE_ID = 1


# settings.py

ASGI_APPLICATION = 'Nexus.asgi.application' # Corrected path to match your project structure
 
# ... (after INSTALLED_APPS) ...




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware', # <<< Add LocaleMiddleware
    'core.middleware.SanitizeLanguageMiddleware', # <<< Add your custom middleware AFTER LocaleMiddleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.GuestAccessRestrictionMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware', # <-- Corrected module name
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # <<< ADD THIS LINE
]

# --- START: Settings for running behind a reverse proxy like ngrok ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True  # For Render/ngrok
SECURE_SSL_REDIRECT = not DEBUG  # In production, force HTTPS

# --- Security Headers and Session Settings ---
# Only apply strict security settings in production (when DEBUG=False)
if not DEBUG:
    # HSTS (HTTP Strict Transport Security) - tells browsers to always use HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session security
    SESSION_COOKIE_SECURE = True  # Only send cookie over HTTPS
    SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
    SESSION_COOKIE_SAMESITE = 'Strict'  # CSRF protection
    
    # CSRF security
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookie over HTTPS
    CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
    CSRF_COOKIE_SAMESITE = 'Strict'  # CSRF protection
else:
    # Development settings - allow insecure cookies
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'

# --- END: Settings for running behind a reverse proxy like ngrok ---


ROOT_URLCONF = 'Nexus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'core.context_processors.provider_info', # <<< Add this line for provider info
                'core.context_processors.categories_processor', # <<< Add this for categories
                'django.template.context_processors.i18n', # Removed 'core.views.menu'
                'core.context_processors.unread_message_count', # <<< Add this for unread messages
                # 'core.views.menu', # <<< THIS WAS THE PROBLEM
                'core.context_processors.currency_context', # <<< Add currency context processor
            ],
            'builtins': [
                'core.templatetags.core_extras',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('DATABASE_URL'):
    # Handle cases where the URL might be quoted in the environment variable
    os.environ['DATABASE_URL'] = os.environ['DATABASE_URL'].strip().strip("'").strip('"')

    db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=True)
    if db_from_env:
        DATABASES['default'] = db_from_env

# --- START: Caching Settings (for django-ratelimit and performance) ---
# Using Redis as the cache backend, since it's already configured for Channels.
# This is required by django-ratelimit for a shared cache.
if DEBUG:
    # Use a simple in-memory cache for development to avoid Redis dependency
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # Production settings using Redis
    REDIS_URL = os.environ.get('REDIS_URL')
    if REDIS_URL:
        CACHES = {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": f"{REDIS_URL}/1",  # Use a different DB number (e.g., 1) from Channels
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                },
                "KEY_PREFIX": "nexus" # Optional: prefix for all cache keys
            }
        }
    else:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }

# Setting for django-ratelimit to use the 'default' cache defined above.
RATELIMIT_USE_CACHE = 'default'
# --- END: Caching Settings ---

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

# --- START: Internationalization Settings ---
LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
    ('es', _('Spanish')),
    ('pt', _('Portuguese')),
    ('zh-hans', _('Chinese Simplified')),
    # Add more languages here as ('code', _('Name'))
]

LOCALE_PATHS = [
    BASE_DIR / 'locale', # Directory where translation files will be stored
]
# --- END: Internationalization Settings ---
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    # Add this line for automatic optimization:
    'EXCLUDE_DELETE_ORPHANED_MEDIA_PATHS': (), # Optional: prevents accidental deletion of folders
    'MAGIC_FILE_PATH': 'magic', # Required for content-type detection in some setups
}

# If using python-dotenv or similar
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
# You will also need to add the webhook secret later
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')
STRIPE_WEBHOOK_SECRET_ASYNC_FAILED = os.environ.get('STRIPE_WEBHOOK_SECRET_ASYNC_FAILED')
STRIPE_WEBHOOK_SECRET_ASYNC_SUCCEEDED = os.environ.get('STRIPE_WEBHOOK_SECRET_ASYNC_SUCCEEDED')

# core/static is automatically found because 'core' is in INSTALLED_APPS.
# Adding it here causes duplicate file warnings.
STATICFILES_DIRS = []

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    'site_header': 'NEXUS',
    'site_brand': 'NEXUS',
    'site_color': '#FF5733',
    'copyright': 'NEXUS INC',
}

AUTH_USER_MODEL = 'authapp.CustomUser'  # Use the custom user model


# settings.py

# ... other settings ...

# Email Configuration (Development - prints to console)
# Use console backend by default to prevent crashes if SMTP is not configured in production yet.
# You can override this with an environment variable when ready for real emails.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# ... rest of your settings ...
# settings.py
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',  # This line might be duplicated below
# ]

# settings.py
# ... (at the end of the file) ...

# django-crispy-forms settings
CRISPY_TEMPLATE_PACK = "bootstrap5" # This is sufficient
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",) # Ensure this is a tuple or list

# settings.py
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, e.g. login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# settings.py
# ...

# settings.py
# ...

# Allauth Settings
# These settings configure django-allauth for email-based authentication,
# while still allowing username collection during signup (as your form does).

ACCOUNT_LOGIN_METHODS = {'email', 'username'}   # Allow login with username or email.
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'  # Must be 'username' if the user model has a username field, even if login is by email.
ACCOUNT_SIGNUP_FIELDS = ['email', 'username']   # Explicitly define signup fields to resolve W001 warning.
ACCOUNT_SIGNUP_FORM_CLASS = 'authapp.forms.UserRegisterForm' # Specify your custom signup form.

ACCOUNT_EMAIL_VERIFICATION = 'optional'         # Options: 'optional', 'mandatory', 'none'.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False     # Align with 'optional' email verification.
ACCOUNT_SESSION_REMEMBER = True                 # Current setting: True. Allows "Remember Me".
ACCOUNT_UNIQUE_EMAIL = True                     # Current setting: True. Enforces unique emails.
if RENDER_EXTERNAL_HOSTNAME:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
else:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'

# Redirect URLs
LOGIN_REDIRECT_URL = 'core:home'  # Name of the URL to redirect to after login
ACCOUNT_LOGOUT_REDIRECT_URL = 'signin' # Name of the URL to redirect to after logout

DEFAULT_CURRENCY_CODE = 'GBP' # Changed to Pounds
DEFAULT_CURRENCY_SYMBOL = '£' # Default symbol
FIXER_API_KEY = os.environ.get('FIXER_API_KEY') # API Key for currency conversion

# --- NEXUS Platform Settings ---
PLATFORM_COMMISSION_RATE = Decimal('0.10') # 10% commission rate
# --- End NEXUS Platform Settings ---


# NEXUS PLATFORM SETTINGS
# ==============================================================================
NEXUS_DELIVERY_COMMISSION_RATE = 0.10  # Example: 10% commission on the delivery fee
# NEXUS_SERVICE_FEE_FIXED = 1.00 # Example: Fixed service fee per order

# settings.py
# ...
PLATFORM_SERVICE_COMMISSION_RATE = 0.10 # Example: 10% commission
# ...


# --- Google Maps API Key ---
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY')



# settings.py
# ...

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         # For each provider, you can define the scope of data you want to request.
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     },
#     'facebook': {
#         'METHOD': 'oauth2', # Set to 'js_sdk' to use the Facebook connect SDK
#         # 'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
#         'SCOPE': ['email', 'public_profile'],
#         'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
#         'INIT_PARAMS': {'cookie': True},
#         'FIELDS': [
#             'id',
#             'first_name',
#             'last_name',
#             'middle_name',
#             'name',
#             'name_format',
#             'picture',
#             'short_name',
#             'email',
#         ],
#         'EXCHANGE_TOKEN': True,
#         # 'LOCALE_FUNC': 'path.to.callable',
#         'VERIFIED_EMAIL': False, # Facebook emails aren't always verified
#         'VERSION': 'v18.0', # Use a specific API version
#     }
# }
SOCIALACCOUNT_PROVIDERS = {}

# Optional: If using custom user model and want social accounts to auto-connect
# SOCIALACCOUNT_ADAPTER = 'your_app.adapter.YourSocialAccountAdapter'

# --- Paystack Settings ---
# Define Paystack settings, allowing them to be None if not set in the environment.
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY')

# c:\Users\Hp\Desktop\Nexus\Nexus\settings.py

# ... other settings ...
# c:\Users\Hp\Desktop\Nexus\nexus\settings.py

# ... (other settings) ...

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'console_format': { # Specific format for console
            'format': '%(levelname)-8s %(asctime)s %(name)-25s %(funcName)-25s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO', # Set to DEBUG to capture INFO and DEBUG logs
            'class': 'logging.StreamHandler',
            'formatter': 'console_format',
        },
        # You can add file handlers here if you want to log to a file
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': BASE_DIR / 'debug.log', # Make sure BASE_DIR is defined
        #     'formatter': 'simple',
        # },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False, # Stop django logs from going to root if root is also console
        },
        'django.request': { # To see request-related errors/warnings
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core': { # Logger for your 'core' app (e.g., core.utils, core.signals)
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False, # Prevent double logging if root also logs to console
        },
        'core.views': { # Specific logger for core.views
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO', # Ensure this is DEBUG
            'propagate': False, # Prevent propagation to 'core' or 'root'
        },
        'authapp': { # Logger for your 'authapp' app
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'numba': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Add other app-specific loggers if needed
    },
    'root': { # Catch-all for other loggers not explicitly defined
        'handlers': ['console'],
        'level': 'INFO', # Set root to INFO to avoid verbose library logs
    }
}

# ... (rest of your settings) ...

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# ... other settings ...

NEGOTIABLE_PRODUCT_CATEGORY_SLUGS = [
    'vehicles', 'cars', 'motorcycles', # Example vehicle categories
    'real-estate', 'houses', 'apartments', 'land-plots', # Example real estate
    'heavy-machinery', 'industrial-equipment', # Example machinery
    # Add any other category slugs that should allow direct payment
]

# --- START: Channels Settings ---
if DEBUG:
    # Use an in-memory channel layer for development to avoid Redis dependency
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    # Production settings using Redis
    REDIS_URL = os.environ.get('REDIS_URL')
    if REDIS_URL:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [f"{REDIS_URL}/2"],
                },
            },
        }
    else:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer"
            }
        }
# --- END: Channels Settings ---

# --- START: Silenced System Checks ---
# Acknowledge and silence non-critical warnings for specific environments.
SILENCED_SYSTEM_CHECKS = [
    'django_ratelimit.W001', # W001: LocMemCache is fine for development.
    'django_ratelimit.E003', # E003: LocMemCache is not a shared cache, but acceptable for development.
    'account.W001', # Silence W001: ACCOUNT_LOGIN_METHODS conflicts with ACCOUNT_SIGNUP_FIELDS
]
# --- END: Silenced System Checks ---

# --- START: Migration Overrides ---
# Store migrations for third-party apps locally to handle schema updates/mismatches.
MIGRATION_MODULES = {
    'ipn': 'core.migrations_ipn',
}
# --- END: Migration Overrides ---

# settings.py

# ... all your other settings ...

# CELERY SETTINGS
# This assumes your Redis instance is available at the URL from the environment variable.
# On Render, this will be automatically set for you if you link the Redis instance.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", os.environ.get("REDIS_URL", "redis://localhost:6379/0"))
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", os.environ.get("REDIS_URL", "redis://localhost:6379/0"))

# Ensure URLs have the correct scheme (fixes issue if only hostname is provided)
if CELERY_BROKER_URL and not CELERY_BROKER_URL.startswith(('redis://', 'rediss://', 'amqp://')):
    if ":" in CELERY_BROKER_URL:
        CELERY_BROKER_URL = f"redis://{CELERY_BROKER_URL}/0"
    else:
        CELERY_BROKER_URL = f"redis://{CELERY_BROKER_URL}:6379/0"

if CELERY_RESULT_BACKEND and not CELERY_RESULT_BACKEND.startswith(('redis://', 'rediss://', 'db+', 'rpc://')):
    if ":" in CELERY_RESULT_BACKEND:
        CELERY_RESULT_BACKEND = f"redis://{CELERY_RESULT_BACKEND}/0"
    else:
        CELERY_RESULT_BACKEND = f"redis://{CELERY_RESULT_BACKEND}:6379/0"

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# --- Storage Configuration ---
STORAGES = {
    "staticfiles": {
        # Use ManifestStaticFilesStorage to skip compression (fixes FileNotFoundError) but keep hashing
        "BACKEND": "core.storage_backends.ForgivingManifestStaticFilesStorage",
    },
    "default": {
        # Use Cloudinary for media in production, but local file system for development
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage" if not DEBUG else "django.core.files.storage.FileSystemStorage",
    },
}

# Legacy settings for compatibility with third-party apps
STATICFILES_STORAGE = "core.storage_backends.ForgivingManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]

WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

# Homepage assistant prompt ranking weights (higher = more relevant priority)
HOME_ASSISTANT_PROMPT_WEIGHTS = {
    'recent_views': 100,
    'buy_again': 90,
    'preferred_category': 80,
    'top_country': 70,
    'verified_sellers': 40,
    'budget_finds': 30,
}
