"""
Django settings for Nexus project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _ # <<< Import for lazy translation

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lmut35poxhw^lr7p=b+w!o9j88cprqn2o^+h)8st^bawhavfe!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '4eec-102-176-94-167.ngrok-free.app'] # Add your ngrok domain


# Application definition

# settings.py

INSTALLED_APPS = [
    # ... your apps first (optional, but common)
    'core.apps.CoreConfig',
    'authapp.apps.AuthappConfig',

    # Django contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',  # <<< Add the sites framework

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'jazzmin',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Specific provider apps:
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.apple', # Removed Apple
]

SITE_ID = 1


# settings.py

# ... (after INSTALLED_APPS) ...

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware', # <<< Add LocaleMiddleware
    'core.middleware.SanitizeLanguageMiddleware', # <<< Add your custom middleware AFTER LocaleMiddleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # <<< ADD THIS LINE
]

# --- START: Settings for running behind a reverse proxy like ngrok ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = False # Set to True in production if your proxy handles SSL termination
# --- END: Settings for running behind a reverse proxy like ngrok ---

ROOT_URLCONF = 'Nexus.urls'

# ... (rest of your settings like TEMPLATES, DATABASES, etc.) ...


ROOT_URLCONF = 'Nexus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.provider_info', # <<< Add this line for provider info
               # 'core.context_processors.cart_context',
                'django.template.context_processors.i18n',
                'core.views.menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'TIMEOUT': 20000,  # Timeout in milliseconds (e.g., 20 seconds)
        # You can also try 'OPTIONS': {'timeout': 20} for seconds,
        # but 'TIMEOUT' at the top level is more common for Django 3.2+
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

# --- START: Internationalization Settings ---
LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    # Add more languages here as ('code', _('Name'))
]

LOCALE_PATHS = [
    BASE_DIR / 'locale', # Directory where translation files will be stored
]
# --- END: Internationalization Settings ---
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core/static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    'site_header': 'NEXUS',
    'site_brand': 'NEXUS',
    'site_color': '#FF5733',
    'copyright': 'NEXUS INC',
}

AUTH_USER_MODEL = 'authapp.CustomUser'  # Use the custom user model


# settings.py

# ... other settings ...

# Email Configuration (Development - prints to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, you would use something like:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.your-email-provider.com'
# EMAIL_PORT = 587 # Or 465 for SSL
# EMAIL_USE_TLS = True # Or EMAIL_USE_SSL = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password-or-app-password'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ... rest of your settings ...
# settings.py
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',  # This line might be duplicated below
# ]

# settings.py
# ... (at the end of the file) ...

# django-crispy-forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# settings.py
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, e.g. login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# settings.py
# ...

# settings.py
# ...

# Allauth Settings
# These settings configure django-allauth for email-based authentication,
# while still allowing username collection during signup (as your form does).

ACCOUNT_AUTHENTICATION_METHODS = ['email']          # Users log in with their email.
ACCOUNT_LOGIN_METHODS = ['email',]               # Users log in with their email.
ACCOUNT_USER_MODEL_USERNAME_FIELD = None        # Important: Set to None if 'username' is not the primary login field.
                                                # This tells allauth not to treat the User model's 'username'
                                                # as the sole login identifier if you're using email for login.

# ACCOUNT_EMAIL_REQUIRED = True                 # Deprecated when ACCOUNT_SIGNUP_FORM_CLASS is used.
                                                # Requirement is handled by the custom form.
# ACCOUNT_USERNAME_REQUIRED = False             # Deprecated when ACCOUNT_SIGNUP_FORM_CLASS is used.
                                                # Requirement is handled by the custom form.
ACCOUNT_SIGNUP_FORM_CLASS = 'authapp.forms.UserRegisterForm' # Specify your custom signup form.
ACCOUNT_SIGNUP_FIELDS = ['email']               # For allauth's internal checks/forms, only 'email' is a signup field.
                                                # ACCOUNT_SIGNUP_FIELDS is not needed when using a custom form class.


ACCOUNT_EMAIL_VERIFICATION = 'optional'         # Options: 'optional', 'mandatory', 'none'.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False     # Align with 'optional' email verification.
# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True    # Commenting out due to deprecation warning; UserCreationForm handles this.
ACCOUNT_SESSION_REMEMBER = True                 # Current setting: True. Allows "Remember Me".
ACCOUNT_UNIQUE_EMAIL = True                     # Current setting: True. Enforces unique emails.
ACCOUNT_LOGOUT_ON_GET = True                    # Current setting: True. Allows logout via GET request.

# Redirect URLs
LOGIN_REDIRECT_URL = 'home'  # Name of the URL to redirect to after login
ACCOUNT_LOGOUT_REDIRECT_URL = 'signin' # Name of the URL to redirect to after logout

# ... (Keep SOCIALACCOUNT_PROVIDERS etc.) ...



# settings.py
# ...

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each provider, you can define the scope of data you want to request.
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'METHOD': 'oauth2', # Set to 'js_sdk' to use the Facebook connect SDK
        # 'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email',
        ],
        'EXCHANGE_TOKEN': True,
        # 'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False, # Facebook emails aren't always verified
        'VERSION': 'v13.0', # Use a specific API version
    }
}

# Optional: If using custom user model and want social accounts to auto-connect
# SOCIALACCOUNT_ADAPTER = 'your_app.adapter.YourSocialAccountAdapter'

# --- Paystack Settings ---
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', 'sk_test_29ce0215ad852bb436a964e2b2b5db7d903948b3') # Replace with your actual test or live key
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', 'pk_test_35b292948ae9ad66a13e64eb04bf17338c8a17dc') # Replace with your actual test or live key
PAYSTACK_CALLBACK_URL = 'https://4eec-102-176-94-167.ngrok-free.app/paystack/callback/' # Use your ngrok URL

# c:\Users\Hp\Desktop\Nexus\Nexus\settings.py

# ... other settings ...

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose', # Use verbose formatter
        },
    },
    'root': { # Catch-all for other loggers
        'handlers': ['console'],
        'level': 'INFO', # Default level for other loggers
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # You can set this to WARNING to reduce Django's own logs
            'propagate': False,
        },
        'core.middleware': { # Logger for our SanitizeLanguageMiddleware
            'handlers': ['console'],
            'level': 'DEBUG', # Show all messages from our middleware
            'propagate': False, # Don't pass to the root logger
        },
    },
}

# ... other settings ...

NEGOTIABLE_PRODUCT_CATEGORY_SLUGS = [
    'vehicles', 'cars', 'motorcycles', # Example vehicle categories
    'real-estate', 'houses', 'apartments', 'land-plots', # Example real estate
    'heavy-machinery', 'industrial-equipment', # Example machinery
    # Add any other category slugs that should allow direct payment
]
