# Generated by Django 5.2 on 2025-04-29 19:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=10)),
                ('full_name', models.CharField(help_text="Recipient's full name", max_length=150)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment_address', models.CharField(blank=True, help_text='Apt, suite, unit, building, floor, etc.', max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='State / Province / Region', max_length=100)),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP / Postal Code')),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default address for this type?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name. Leave blank to auto-generate.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the category.', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this category currently visible/usable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Assign if this is a subcategory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='Unique order identifier (e.g., NEXUS-YYYYMMDD-XXXXX). Auto-generated.', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_address_text', models.TextField(blank=True, help_text='Snapshot of shipping address at time of order.', null=True)),
                ('billing_address_text', models.TextField(blank=True, help_text='Snapshot of billing address at time of order.', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the order.', null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='core.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='core.address')),
                ('user', models.ForeignKey(blank=True, help_text='User who placed the order. Null if guest or user deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name. Leave blank to auto-generate.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD (or your base currency).', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main product image.', null=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of items currently in stock.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is the product available for purchase?')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Should this product be featured (e.g., on homepage)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Snapshot of product name at time of order.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of order.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(blank=True, help_text='Link to the product. Null if product deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ('order', 'product_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'address_type'), name='unique_default_address_per_type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'id'], name='core_produc_slug_f51155_idx'),
        ),
    ]
