# Generated by Django 5.2 on 2025-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_completion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Customer Confirmed Completion At'),
        ),
    ]
