# Generated by Django 5.2 on 2025-05-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_customer_confirmed_completion_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Profile URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='public_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Public Email Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='public_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Public Phone Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter (X) Profile URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g., +12345678900. This will be visible.', max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
