# Generated by Django 5.2 on 2025-04-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wishlistitem_alter_order_order_id_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this vendor been verified by NEXUS staff (e.g., identity checked)?'),
        ),
    ]
