# Generated by Django 5.2 on 2025-05-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendor_facebook_url_vendor_instagram_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, help_text='If different from your personal name.', max_length=255, null=True, verbose_name='Business Name (Optional)')),
                ('bio', models.TextField(help_text='Describe your services, experience, and what you offer.', verbose_name='Service Provider Bio/Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Profile Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
