# Generated by Django 5.2 on 2025-05-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceproviderprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title (Optional)')),
                ('description', models.TextField(blank=True, verbose_name='Description (Optional)')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of your work.', null=True, upload_to='service_provider_portfolio/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='Link to a video showcasing your work. This will be embedded.', null=True, verbose_name='Video URL (e.g., YouTube, Vimeo)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='core.serviceproviderprofile', verbose_name='Provider Profile')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
