# Generated by Django 5.2 on 2025-05-01 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload a product video (MP4, WebM recommended).', upload_to='products/videos/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the video.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
