# Generated by Django 5.2 on 2025-05-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: Upload a short video review (MP4, WebM recommended).', null=True, upload_to='reviews/videos/'),
        ),
    ]
