# Generated by Django 5.2 on 2025-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_abtest_blogcategory_coupon_currency_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradditionalinfo',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
