# Generated by Django 5.2 on 2025-05-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendoradditionalinfo_terms_agreed_and_more'),
    ]

    operations = [
    ]
