# Generated by Django 5.2 on 2025-05-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='payout_mobile_money_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Payout Mobile Money Number'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='payout_mobile_money_provider',
            field=models.CharField(blank=True, choices=[('', 'Select Provider'), ('MTN', 'MTN Mobile Money'), ('VODAFONE', 'Vodafone Cash'), ('AIRTELTIGO', 'AirtelTigo Money')], max_length=50, null=True, verbose_name='Payout Mobile Money Provider'),
        ),
    ]
