# Generated by Django 5.2 on 2025-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendor_contact_email_vendor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_registration_doc',
            field=models.FileField(blank=True, help_text='Upload proof of business registration (if applicable).', null=True, upload_to='vendors/registration_docs/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='national_id_doc',
            field=models.FileField(blank=True, help_text='Upload copy of National ID (if business is not registered).', null=True, upload_to='vendors/national_ids/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID Number (if business is not registered).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='national_id_type',
            field=models.CharField(blank=True, help_text='Type of National ID provided (e.g., Ghana Card).', max_length=50, null=True),
        ),
    ]
