# Generated by Django 5.2 on 2025-05-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_serviceproviderprofile_payout_mobile_money_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Paystack Recipient Code'),
        ),
    ]
