# Generated by Django 5.2 on 2025-05-03 06:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendor_business_registration_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Money Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_money_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Money Provider'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='other_business_doc',
            field=models.FileField(blank=True, null=True, upload_to=core.models.vendor_directory_path, verbose_name='Other Supporting Document (Optional)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Identification Number (TIN)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_registration_doc',
            field=models.FileField(blank=True, null=True, upload_to=core.models.vendor_directory_path, verbose_name='Business Registration Document'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo for the vendor.', null=True, upload_to=core.models.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='national_id_doc',
            field=models.FileField(blank=True, null=True, upload_to=core.models.vendor_directory_path, verbose_name='National ID Document'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='national_id_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of National ID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='return_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Return Policy'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Policy'),
        ),
    ]
