# Generated by Django 5.2 on 2025-05-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendor_mobile_money_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the campaign.', max_length=255)),
                ('placement', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('search_results_top', 'Search Results (Top)'), ('category_sidebar', 'Category Sidebar')], help_text='Where the ad will be displayed.', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for the campaign (optional).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the campaign currently running?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_product', models.ForeignKey(blank=True, help_text='Product being promoted (optional, if promoting the vendor store itself).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.product')),
                ('vendor', models.ForeignKey(help_text='The vendor running the campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Ad Campaign',
                'verbose_name_plural': 'Ad Campaigns',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for the promotion (e.g., 'Summer Sale 20% Off')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for customers.')),
                ('code', models.CharField(blank=True, help_text='Coupon code users enter (optional, leave blank for automatic discounts).', max_length=50, null=True, unique=True)),
                ('promo_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20.00 for 20%) or fixed amount.', max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category'), ('product', 'Specific Product(s)'), ('vendor', 'Specific Vendor')], default='all', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When the promotion becomes active.')),
                ('end_date', models.DateTimeField(help_text='When the promotion expires.')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required to apply (optional).', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promotion can be used in total (optional).', null=True)),
                ('uses_per_customer', models.PositiveIntegerField(blank=True, help_text='Maximum number of times a single customer can use this promotion (optional).', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Is this promotion currently active (within dates and usage limits)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text="Select categories if scope is 'Specific Category'.", related_name='promotions', to='core.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text="Select products if scope is 'Specific Product(s)'.", related_name='promotions', to='core.product')),
                ('applicable_vendor', models.ForeignKey(blank=True, help_text="Select vendor if scope is 'Specific Vendor'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ('-start_date',),
            },
        ),
    ]
