# Generated by Django 5.2 on 2025-05-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_serviceproviderprofile_paystack_recipient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Payout to Vendor/Provider'), ('platform_commission', 'Platform Commission'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release')], max_length=20),
        ),
    ]
