# Generated by Django 5.2 on 2025-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_confirmed_completion_at',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Customer Confirmed Delivery/Completion'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment Choice'), ('AWAITING_ESCROW_PAYMENT', 'Awaiting Escrow Payment'), ('AWAITING_DIRECT_PAYMENT', 'Awaiting Direct Payment Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('PENDING_PAYOUT', 'Pending Payout to Provider'), ('IN_PROGRESS', 'Service In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded'), ('pending', 'Pending (Product Order)'), ('processing', 'Processing (Product Order)'), ('shipped', 'Shipped (Product Order)'), ('delivered', 'Delivered (Product Order)'), ('cancelled', 'Cancelled (Product Order)'), ('refunded', 'Refunded (Product Order)')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
