# Generated by Django 5.2 on 2025-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_customer_confirmed_completion_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Paystack Recipient Code (for Vendor Payouts)'),
        ),
    ]
