# Generated by Django 5.2 on 2025-05-16 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vendor_paystack_recipient_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Your primary contact number for deliveries.', max_length=20, null=True, verbose_name='Phone Number')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('other', 'Other')], default='motorcycle', max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle Registration Number')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="Driver's License Number")),
                ('address', models.TextField(blank=True, help_text='Primary area you operate in.', null=True, verbose_name='Operating Address / Area')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the rider has been approved by platform admins.', verbose_name='Approved by Admin')),
                ('is_available', models.BooleanField(default=False, help_text='Is the rider currently available to take new delivery assignments?', verbose_name='Available for Deliveries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
            },
        ),
    ]
