# Generated by Django 5.2 on 2025-05-16 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_riderprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rider Profile', 'verbose_name_plural': 'Rider Profiles'},
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address_text', models.TextField(verbose_name='Pickup Address Snapshot')),
                ('delivery_address_text', models.TextField(verbose_name='Delivery Address Snapshot')),
                ('status', models.CharField(choices=[('PENDING_ASSIGNMENT', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Rider'), ('ACCEPTED_BY_RIDER', 'Accepted by Rider'), ('REJECTED_BY_RIDER', 'Rejected by Rider'), ('PICKED_UP', 'Picked Up from Vendor'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('CANCELLED_BY_VENDOR', 'Cancelled by Vendor'), ('CANCELLED_BY_ADMIN', 'Cancelled by Admin'), ('FAILED_DELIVERY', 'Failed Delivery Attempt')], default='PENDING_ASSIGNMENT', max_length=30, verbose_name='Status')),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Pickup Time')),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Pickup Time')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery Time')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Time')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='core.order', verbose_name='Order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='core.riderprofile', verbose_name='Assigned Rider')),
            ],
            options={
                'verbose_name': 'Delivery Task',
                'verbose_name_plural': 'Delivery Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
