# Generated by Django 5.2 on 2025-05-17 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_riderprofile_options_deliverytask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Your primary contact number for deliveries.', max_length=20, verbose_name='Phone Number')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('other', 'Other')], default='motorcycle', max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle Registration Number')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="Driver's License Number")),
                ('address', models.TextField(help_text='Primary area you operate in.', verbose_name='Operating Address / Area')),
                ('vehicle_registration_document', models.FileField(blank=True, null=True, upload_to='rider_applications/docs/', verbose_name='Vehicle Registration Document')),
                ('drivers_license_front', models.FileField(blank=True, null=True, upload_to='rider_applications/docs/', verbose_name="Driver's License (Front)")),
                ('drivers_license_back', models.FileField(blank=True, null=True, upload_to='rider_applications/docs/', verbose_name="Driver's License (Back)")),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='rider_applications/docs/', verbose_name='National ID (Front)')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='rider_applications/docs/', verbose_name='National ID (Back)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='rider_applications/profile_pics/', verbose_name='Profile Picture')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Agreed to Terms')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed by Admin')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
