# Generated by Django 5.2 on 2025-05-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_riderapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderapplication',
            name='vehicle_picture',
            field=models.ImageField(blank=True, null=True, upload_to='rider_applications/vehicle_pics/', verbose_name='Picture of Vehicle'),
        ),
    ]
