# Generated by Django 5.2 on 2025-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_riderapplication_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderapplication',
            name='drivers_license_back',
            field=models.FileField(default='', upload_to='rider_applications/docs/', verbose_name="Driver's License (Back)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderapplication',
            name='drivers_license_front',
            field=models.FileField(default='', upload_to='rider_applications/docs/', verbose_name="Driver's License (Front)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderapplication',
            name='license_number',
            field=models.CharField(default='', max_length=50, verbose_name="Driver's License Number"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderapplication',
            name='vehicle_picture',
            field=models.ImageField(default='', upload_to='rider_applications/vehicle_pics/', verbose_name='Picture of Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderapplication',
            name='vehicle_registration_number',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Registration Number'),
            preserve_default=False,
        ),
    ]
