# Generated by Django 5.2 on 2025-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_riderapplication_drivers_license_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='current_drivers_license_back',
            field=models.FileField(blank=True, help_text="Current driver's license (back).", null=True, upload_to='rider_profiles/licenses/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_drivers_license_front',
            field=models.FileField(blank=True, help_text="Current driver's license (front).", null=True, upload_to='rider_profiles/licenses/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_id_card_back',
            field=models.FileField(blank=True, help_text='Current national ID card (back).', null=True, upload_to='rider_profiles/ids/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_id_card_front',
            field=models.FileField(blank=True, help_text='Current national ID card (front).', null=True, upload_to='rider_profiles/ids/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_vehicle_picture',
            field=models.FileField(blank=True, help_text='Current picture of the vehicle.', null=True, upload_to='rider_profiles/vehicle_pictures/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_vehicle_registration_document',
            field=models.FileField(blank=True, help_text='Current vehicle registration document.', null=True, upload_to='rider_profiles/registrations/'),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Vehicle Registration Number'),
        ),
    ]
