# Generated by Django 5.2 on 2025-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_riderprofile_current_drivers_license_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 24-Hour Search Boost, 7-Day Featured Rider', max_length=100, unique=True, verbose_name='Package Name')),
                ('description', models.TextField(help_text='Detailed description of what this boost package offers.', verbose_name='Description')),
                ('boost_type', models.CharField(choices=[('search_top', 'Top of Search Results'), ('featured_profile', 'Featured Profile Section')], max_length=50, verbose_name='Boost Type')),
                ('duration_hours', models.PositiveIntegerField(help_text='How long this boost will be active once purchased.', verbose_name='Duration (in hours)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of this boost package in GHS.', max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Is this package currently available for purchase?', verbose_name='Is Active?')),
                ('icon_class', models.CharField(blank=True, help_text='e.g., fas fa-rocket, fas fa-star', max_length=50, null=True, verbose_name='Font Awesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which packages are displayed to riders.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boost Package',
                'verbose_name_plural': 'Boost Packages',
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
