# Generated by Django 5.2 on 2025-05-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_boostpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRiderBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Activated At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, help_text='Automatically set based on expiry. Can be manually overridden.', verbose_name='Is Currently Active?')),
                ('boost_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='core.boostpackage', verbose_name='Boost Package')),
                ('rider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_boosts', to='core.riderprofile', verbose_name='Rider Profile')),
            ],
        ),
    ]
