# Generated by Django 5.2 on 2025-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_activeriderboost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Payout to Vendor/Provider'), ('platform_commission', 'Platform Commission'), ('boost_purchase', 'Rider Boost Purchase'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release')], max_length=20),
        ),
    ]
