# Generated by Django 5.2 on 2025-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delivery Fee'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Platform Commission for this Task'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='rider_earning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rider Earning for this Task'),
        ),
    ]
