# Generated by Django 5.2 on 2025-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_method',
            field=models.CharField(choices=[('nexus', 'Fulfilled by Nexus'), ('vendor', 'Fulfilled by Vendor')], default='vendor', max_length=10, verbose_name='Fulfillment Method'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_fulfillment_method',
            field=models.CharField(choices=[('nexus', 'Fulfilled by Nexus'), ('vendor', 'Fulfilled by Vendor')], default='vendor', max_length=10, verbose_name='Default Fulfillment Method'),
        ),
    ]
