# Generated by Django 5.2 on 2025-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_orderitem_fulfillment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_method',
            field=models.CharField(blank=True, choices=[('nexus', 'Fulfilled by Nexus'), ('vendor', 'Fulfilled by Vendor')], help_text="Leave blank to use vendor's default setting.", max_length=10, null=True, verbose_name='Product Fulfillment Method'),
        ),
    ]
