# Generated by Django 5.2 on 2025-05-18 21:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_fulfillment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Set this if you fulfill this product yourself and want to charge a specific delivery fee. Only applies if 'Product Fulfillment Method' is 'Fulfilled by Vendor'.", max_digits=10, null=True, verbose_name="Vendor's Delivery Fee (if FBM)"),
        ),
    ]
