# Generated by Django 5.2 on 2025-05-18 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_product_vendor_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Platform (Nexus) Delivery Fee Component'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery charge specifically for this item, if applicable (e.g., vendor-set).', max_digits=10, verbose_name='Item Delivery Charge'),
        ),
    ]
