# Generated by Django 5.2 on 2025-05-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_platform_delivery_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Requested')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('processing', 'Processing Payout'), ('completed', 'Payout Completed'), ('rejected', 'Payout Rejected'), ('failed', 'Payout Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin regarding this payout request (e.g., reason for rejection).', null=True, verbose_name='Admin Notes')),
                ('rider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.riderprofile', verbose_name='Rider')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_request_fulfilled', to='core.transaction', verbose_name='Fulfilled by Transaction')),
            ],
            options={
                'verbose_name': 'Rider Payout Request',
                'verbose_name_plural': 'Rider Payout Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
