# Generated by Django 5.2 on 2025-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precise latitude for the address.', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precise longitude for the address.', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Delivery Latitude'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Delivery Longitude'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Pickup Latitude'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Pickup Longitude'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Current Latitude'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Current Longitude'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Vendor's precise latitude for pickup.", max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Vendor's precise longitude for pickup.", max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
