# Generated by Django 5.2 on 2025-05-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='street_address',
            field=models.CharField(blank=True, help_text="Street address for the vendor's physical location.", max_length=255, null=True),
        ),
    ]
