# Generated by Django 5.2 on 2025-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_vendor_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='payment_method_details',
            field=models.TextField(blank=True, help_text='E.g., Bank Name, Account Number, Mobile Money Number & Name.', null=True, verbose_name='Payment Method Details'),
        ),
    ]
