# Generated by Django 5.2 on 2025-05-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_payoutrequest_payment_method_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='rider_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.riderprofile', verbose_name='Rider'),
        ),
    ]
