# Generated by Django 5.2 on 2025-05-20 23:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_payoutrequest_vendor_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_registration_document',
            field=models.FileField(blank=True, help_text='e.g., Business Registration Certificate, Certificate of Incorporation', null=True, upload_to=core.models.vendor_directory_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False, help_text='Has this vendor been manually verified by an admin?'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='national_id_document',
            field=models.FileField(blank=True, help_text='Scanned copy of the National ID document.', null=True, upload_to=core.models.vendor_directory_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='other_supporting_document',
            field=models.FileField(blank=True, help_text='Any other supporting document for business verification.', null=True, upload_to=core.models.vendor_directory_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Identification Number (TIN)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verification_documents_submitted',
            field=models.BooleanField(default=False, help_text='Have any verification documents been submitted?'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('BUSINESS', 'I have a registered business'), ('INDIVIDUAL', 'I am registering as an individual (using National ID)')], help_text='How is the vendor verifying their identity/business?', max_length=20, null=True, verbose_name='Verification Method'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verification_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_RESUBMISSION', 'Needs Resubmission')], default='NOT_SUBMITTED', help_text='Current status of vendor verification.', max_length=20, verbose_name='Verification Status'),
        ),
    ]
