# Generated by Django 5.2 on 2025-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_vendor_business_registration_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_registration_doc',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='national_id_doc',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='other_business_doc',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tin_number',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='national_id_type',
            field=models.CharField(blank=True, help_text="e.g., National ID Card, Passport, Driver's License", max_length=50, null=True, verbose_name='Type of National ID'),
        ),
    ]
