# Generated by Django 5.2 on 2025-05-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_vendor_business_registration_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Payout Request', 'verbose_name_plural': 'Payout Requests'},
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='service_provider_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.serviceproviderprofile', verbose_name='Service Provider'),
        ),
    ]
