# Generated by Django 5.2 on 2025-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_payoutrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords_for_ai',
            field=models.CharField(blank=True, help_text='Optional: Comma-separated keywords to guide AI description generation (e.g., durable, eco-friendly, best gift).', max_length=255, null=True, verbose_name='Keywords for AI Description'),
        ),
    ]
