# Generated by Django 5.2.3 on 2025-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_product_keywords_for_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='three_d_model',
            field=models.FileField(blank=True, help_text='Upload a 3D model file (e.g., .glb, .gltf) for 3D viewing.', null=True, upload_to='products/3d_models/', verbose_name='3D Model File'),
        ),
    ]
