# Generated by Django 5.2.3 on 2025-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_product_three_d_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='has_premium_3d_generation_access',
            field=models.BooleanField(default=False, help_text='Grants access to the AI-powered 3D model generation feature.', verbose_name='Premium 3D Generation Access'),
        ),
    ]
