# Generated by Django 5.2.3 on 2025-07-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_vendor_has_premium_3d_generation_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('plan_type', models.CharField(choices=[('vendor_premium', 'Vendor Premium Plan')], default='vendor_premium', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='GHS', help_text='ISO 4217 currency code.', max_length=3)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration of the plan in days (e.g., 30 for monthly, 365 for yearly).')),
                ('features', models.TextField(blank=True, help_text='List of features, one per line.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan available for purchase?')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Payout to Vendor/Provider'), ('platform_commission', 'Platform Commission'), ('vendor_plan_purchase', 'Vendor Plan Purchase'), ('boost_purchase', 'Rider Boost Purchase'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release')], max_length=20),
        ),
    ]
