# Generated by Django 5.2.3 on 2025-07-13 06:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_pricingplan_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpayment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorshipping',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='activeriderboost',
            options={'ordering': ['-expires_at', 'rider_profile'], 'verbose_name': 'Active Rider Boost', 'verbose_name_plural': 'Active Rider Boosts'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Product Video'},
        ),
        migrations.AlterModelOptions(
            name='serviceproviderprofile',
            options={'verbose_name': 'Service Provider Profile', 'verbose_name_plural': 'Service Provider Profiles'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='delivery_address_text',
            field=models.TextField(verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='pickup_address_text',
            field=models.TextField(blank=True, verbose_name='Pickup Address'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission earned by the platform for this delivery.', max_digits=10, null=True, verbose_name='Platform Commission'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='rider_earning',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the rider earns from this delivery.', max_digits=10, null=True, verbose_name='Rider Earning'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('PENDING_ASSIGNMENT', 'Pending Assignment'), ('ACCEPTED_BY_RIDER', 'Accepted by Rider'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING_ASSIGNMENT', max_length=30, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='task_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Task ID'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload a short video review (MP4, WebM recommended).', upload_to='reviews/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Is this review visible to the public? (For moderation)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reviews', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Review',
                'verbose_name_plural': 'Video Reviews',
                'ordering': ('-created_at',),
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='VendorAdditionalInfo',
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
        migrations.DeleteModel(
            name='VendorShipping',
        ),
    ]
