# Generated by Django 5.2.4 on 2025-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_userprofile_github_url_userprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Payout to Vendor/Provider'), ('platform_commission', 'Platform Commission'), ('vendor_plan_purchase', 'Vendor Plan Purchase'), ('boost_purchase', 'Rider Boost Purchase'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('reward_redemption', 'Reward Redemption')], max_length=20),
        ),
    ]
