# Generated by Django 5.2.4 on 2025-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='points_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Points Cost'),
        ),
    ]
