# Generated by Django 5.2.4 on 2025-07-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_order_tip_amount_productquestion_productanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, help_text='The vendor selling this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.vendor'),
        ),
    ]
