# Generated by Django 5.2.4 on 2025-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_message_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vendorreview',
            name='comment',
        ),
        migrations.AddField(
            model_name='servicereview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Review'),
        ),
    ]
