# Generated by Django 5.2.4 on 2025-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_servicereview_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_model',
            field=models.FileField(blank=True, help_text='Upload a .glb or .usdz file for the AR experience.', null=True, upload_to='ar_models/', verbose_name='AR 3D Model'),
        ),
    ]
