# Generated by Django 5.2.4 on 2025-09-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_ar_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicepackage'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='GHS', help_text='Currency of the order (e.g., GHS, USD)', max_length=3),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('escrow', 'Escrow (Paystack)'), ('direct', 'Direct Arrangement'), ('paypal', 'PayPal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment Choice'), ('AWAITING_ESCROW_PAYMENT', 'Awaiting Escrow Payment'), ('AWAITING_DIRECT_PAYMENT', 'Awaiting Direct Payment'), ('PROCESSING', 'Processing'), ('IN_PROGRESS', 'Service In Progress'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PENDING_PAYOUT', 'Pending Payout'), ('COMPLETED', 'Completed & Paid Out'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product'), ('cart', 'service_package')},
        ),
    ]
