# Generated by Django 5.2.4 on 2025-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_savedforlateritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment Choice'), ('AWAITING_ESCROW_PAYMENT', 'Awaiting Escrow Payment'), ('AWAITING_DIRECT_PAYMENT', 'Awaiting Direct Payment'), ('ON_HOLD_FRAUD_REVIEW', 'On Hold (Fraud Review)'), ('PROCESSING', 'Processing'), ('IN_PROGRESS', 'Service In Progress'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PENDING_PAYOUT', 'Pending Payout'), ('COMPLETED', 'Completed & Paid Out'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
