# Generated by Django 5.2.4 on 2025-09-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bank Account Holder's Name"),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Branch Name/Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PayPal Email Address'),
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_report', to='core.order')),
            ],
            options={
                'verbose_name': 'Fraud Report',
                'verbose_name_plural': 'Fraud Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
