# Generated by Django 5.2.4 on 2025-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_vendor_bank_account_name_vendor_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cryptocurrency Wallet Address'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='crypto_wallet_network',
            field=models.CharField(blank=True, help_text='e.g., Bitcoin, Ethereum (ERC20), Tron (TRC20), etc.', max_length=50, null=True, verbose_name='Crypto Network'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='payoneer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Payoneer Email Address'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Your Stripe Connect account ID (e.g., acct_xxxxxxxx).', max_length=255, null=True, verbose_name='Stripe Connect Account ID'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='wise_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Wise (formerly TransferWise) Email Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cryptocurrency Wallet Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='crypto_wallet_network',
            field=models.CharField(blank=True, help_text='e.g., Bitcoin, Ethereum (ERC20), Tron (TRC20), etc.', max_length=50, null=True, verbose_name='Crypto Network'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payoneer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Payoneer Email Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Your Stripe Connect account ID (e.g., acct_xxxxxxxx).', max_length=255, null=True, verbose_name='Stripe Connect Account ID'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='wise_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Wise (formerly TransferWise) Email Address'),
        ),
    ]
