# Generated by Django 5.2.4 on 2025-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_serviceproviderprofile_crypto_wallet_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='current_uses',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_purchase_amount',
        ),
        migrations.AddField(
            model_name='promotion',
            name='minimum_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The promotion will only apply if the cart total is above this amount. Leave blank for no minimum.', max_digits=10, null=True, verbose_name='Minimum Purchase Amount'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The number of times this promotion has been used.', verbose_name='Usage Count'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='The total number of times this promotion can be used. Leave blank for unlimited uses.', null=True, verbose_name='Usage Limit'),
        ),
    ]
