# Generated by Django 5.2.4 on 2025-09-23 19:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_promotion_current_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total discount amount applied to the order.', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='The promotion applied to this order, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.promotion'),
        ),
    ]
