# Generated by Django 5.2.4 on 2025-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_order_discount_amount_order_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Replied At'),
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Vendor Reply'),
        ),
    ]
