# Generated by Django 5.2.4 on 2025-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_vendorreview_replied_at_vendorreview_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for your portfolio item.', null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='link',
            field=models.URLField(blank=True, help_text='Or, provide a link to a video (e.g., YouTube, Vimeo) or external project.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='portfolioitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('link__isnull', True)), models.Q(('image__isnull', True), ('link__isnull', False)), _connector='OR'), name='image_or_link_present', violation_error_message='A portfolio item must have either an image or a link, but not both.'),
        ),
    ]
