# Generated by Django 5.2.4 on 2025-09-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_portfolioitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviderprofile',
            old_name='payout_mobile_money_number',
            new_name='mobile_money_number',
        ),
        migrations.RenameField(
            model_name='serviceproviderprofile',
            old_name='payout_mobile_money_provider',
            new_name='mobile_money_provider',
        ),
    ]
