# Generated by Django 5.2.4 on 2025-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_payout_mobile_money_number_serviceproviderprofile_mobile_money_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bank Account Holder's Name"),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Branch Name/Address'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PayPal Email Address'),
        ),
    ]
