# Generated by Django 5.2.4 on 2025-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_serviceproviderprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='story',
            field=models.TextField(blank=True, help_text='Share the story behind your brand. This will be visible on your public profile.', null=True, verbose_name='Our Story'),
        ),
    ]
