# Generated by Django 5.2.4 on 2025-12-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_vendor_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor selling this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.vendor'),
        ),
    ]
