# Generated by Django 5.1.15 on 2026-01-06 02:44

from django.db import migrations
import os

def create_default_site(apps, schema_editor):
    """
    Creates the default Site object with ID=1 if it doesn't exist.
    This prevents 'Site matching query does not exist' 500 errors in production.
    """
    Site = apps.get_model('sites', 'Site')
    
    # Get domain from environment variable, fallback to Render URL
    domain = os.environ.get('DOMAIN_NAME', 'gowbuy-project.onrender.com')

    # We use ID=1 because SITE_ID = 1 in settings.py
    # Use update_or_create to ensure the domain is correct even if the ID exists (e.g. default example.com)
    site, created = Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': domain,
            'name': 'Nexus',
        }
    )

    # FIX for DoesNotExist at /signin/:
    # Ensure a SocialApp exists for your provider (e.g., Google) and is linked to this Site.
    # Uncomment and adapt the lines below if you want to automate this:
    
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    google_app, _ = SocialApp.objects.update_or_create(
        provider='google', 
        defaults={
            'name': 'Google', 
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', 'YOUR_GOOGLE_CLIENT_ID'), 
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', 'YOUR_GOOGLE_SECRET')
        }
    )
    google_app.sites.add(site)

    facebook_app, _ = SocialApp.objects.update_or_create(
        provider='facebook', 
        defaults={
            'name': 'Facebook', 
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID', 'YOUR_FACEBOOK_CLIENT_ID'), 
            'secret': os.environ.get('FACEBOOK_CLIENT_SECRET', 'YOUR_FACEBOOK_SECRET')
        }
    )
    facebook_app.sites.add(site)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_product_vendor'),
        ('sites', '0002_alter_domain_unique'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_site),
    ]
