# Generated by Django 5.1.15 on 2026-01-06 02:44

from django.db import migrations

def create_default_site(apps, schema_editor):
    """
    Creates the default Site object with ID=1 if it doesn't exist.
    This prevents 'Site matching query does not exist' 500 errors in production.
    """
    Site = apps.get_model('sites', 'Site')
    
    # We use ID=1 because SITE_ID = 1 in settings.py
    if not Site.objects.filter(id=1).exists():
        Site.objects.create(
            id=1, 
            domain='gowbuy-project.onrender.com', 
            name='Nexus'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_product_vendor'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_default_site),
    ]
