# Generated by Django 5.1.15 on 2026-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('escrow', 'Escrow (Paystack)'), ('direct', 'Direct Arrangement'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card'), ('digital_wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment Choice'), ('AWAITING_ESCROW_PAYMENT', 'Awaiting Escrow Payment'), ('AWAITING_DIRECT_PAYMENT', 'Awaiting Direct Payment'), ('AWAITING_BANK_TRANSFER', 'Awaiting Bank Transfer'), ('ON_HOLD_FRAUD_REVIEW', 'On Hold (Fraud Review)'), ('PROCESSING', 'Processing'), ('IN_PROGRESS', 'Service In Progress'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PENDING_PAYOUT', 'Pending Payout'), ('COMPLETED', 'Completed & Paid Out'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
