# Generated by Django 5.1.15 on 2026-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the customer at the time of order.', null=True),
        ),
    ]
