# Generated by Django 5.1.15 on 2026-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_order_tracking_number_order_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('escrow', 'Escrow (Secure Payment)'), ('direct', 'Direct Arrangement'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card'), ('digital_wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
