# Generated by Django 5.1.15 on 2026-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by_users', to='core.service'),
        ),
    ]
