# Generated by Django 5.1.15 on 2026-01-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_wishlist_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='location_address',
            field=models.ForeignKey(blank=True, help_text='Address where the service will be performed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='core.address'),
        ),
    ]
