# Generated by Django 5.1.15 on 2026-01-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_servicebooking_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Contact Email'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Business Phone Number'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_providers/images/', verbose_name='Profile Image/Logo'),
        ),
    ]
