# Generated by Django 5.1.15 on 2026-01-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_serviceproviderprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='bio',
            field=models.TextField(default='', help_text='Describe your services, experience, and what you offer.', verbose_name='Service Provider Bio/Description'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_name',
            field=models.CharField(default='', help_text='If different from your personal name.', max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Business Contact Email'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Business Phone Number'),
        ),
    ]
