# Generated by Django 5.1.15 on 2026-01-30 08:20

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_serviceproviderprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, help_text='Country of origin for this product.', max_length=2, null=True, verbose_name='Origin Country'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['origin_country'], name='core_produc_origin__c73cce_idx'),
        ),
    ]
