# Generated by Django 5.1.15 on 2026-01-31 08:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_origin_inference_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originlabel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Origin Label', 'verbose_name_plural': 'Origin Labels'},
        ),
        migrations.AlterField(
            model_name='origininferencejob',
            name='params',
            field=models.JSONField(blank=True, help_text='Parameters used for the run (e.g., min_confidence)', null=True),
        ),
        migrations.AlterField(
            model_name='origininferencejob',
            name='summary',
            field=models.JSONField(blank=True, help_text='Summary produced by the prediction run', null=True),
        ),
        migrations.AlterField(
            model_name='originlabel',
            name='label_country',
            field=django_countries.fields.CountryField(blank=True, help_text="Labeled origin country (can be null for 'unknown' or rejected label)", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='originlabel',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('import', 'Import'), ('auto', 'Automatic')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for suggested origin in [0..1].', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_inference_metadata',
            field=models.JSONField(blank=True, help_text='JSON metadata/evidence for the suggestion (e.g., rules matched, features).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_inference_status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('none', 'None')], default='none', help_text='Status of the suggested origin.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_inferred_by',
            field=models.CharField(blank=True, choices=[('rule', 'Rule-based'), ('ml', 'ML-model'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggested_origin_country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, help_text='Origin country suggested by automated inference (admin review required).', max_length=2, null=True, verbose_name='Suggested Origin Country'),
        ),
    ]
