# Generated by Django 5.1.15 on 2026-01-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_originlabel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticity_status',
            field=models.CharField(blank=True, choices=[('authentic', 'Authentic (Original)'), ('refurbished', 'Refurbished'), ('replica', 'Replica/Homage'), ('unknown', 'Unknown')], default='unknown', help_text='Product authenticity status. For physical products: set by vendor or inferred by system.', max_length=20, verbose_name='Authenticity Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='authenticity_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when authenticity was last verified/updated.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='product',
            name='authenticity_verified_by',
            field=models.CharField(blank=True, help_text="Who verified the authenticity: 'vendor', 'admin', 'ml', etc.", max_length=50, null=True, verbose_name='Verified By'),
        ),
    ]
