# Generated by Django 5.1.15 on 2026-01-31 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_authenticity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Authenticity Labs Inc'", max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('stripe_radar', 'Stripe Radar'), ('custom_api', 'Custom API'), ('manual', 'Manual Third-party')], max_length=20)),
                ('api_endpoint', models.URLField(blank=True, help_text='Webhook/API endpoint for verification requests')),
                ('api_key', models.CharField(blank=True, help_text='Encrypted API key for authentication', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verification Provider',
                'verbose_name_plural': 'Verification Providers',
            },
        ),
        migrations.CreateModel(
            name='AuthenticityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('suspected_fake', 'Suspected Fake/Counterfeit'), ('quality_mismatch', "Quality Doesn't Match Description"), ('wrong_origin', 'Origin Seems Incorrect'), ('other', 'Other Authenticity Concern')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the authenticity concern')),
                ('order_id', models.CharField(blank=True, help_text='Order ID if purchased', max_length=100)),
                ('image_evidence', models.ImageField(blank=True, help_text='Photo evidence (e.g., packaging, label, etc.)', null=True, upload_to='authenticity_evidence/')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this report been verified by admin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity_feedback', to='core.product')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authenticity Feedback',
                'verbose_name_plural': 'Authenticity Feedback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthenticityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified - Authentic'), ('suspicious', 'Suspicious - Needs Investigation'), ('rejected', 'Rejected - Not Authentic'), ('cleared', 'Cleared - No Issues Found')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for review or findings')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticity_reviews_flagged', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity_reviews', to='core.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticity_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authenticity Review',
                'verbose_name_plural': 'Authenticity Reviews',
                'ordering': ('-flagged_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthenticityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_trust_score', models.FloatField(default=50, help_text='Based on vendor history, returns, disputes')),
                ('buyer_feedback_score', models.FloatField(default=50, help_text='Based on negative feedback count')),
                ('admin_review_score', models.FloatField(default=50, help_text='Based on admin verification status')),
                ('third_party_score', models.FloatField(default=50, help_text='Based on third-party verification results')),
                ('overall_score', models.FloatField(default=50, help_text='Weighted composite score 0-100')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('update_reason', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity_score', to='core.product')),
            ],
            options={
                'verbose_name': 'Authenticity Score',
                'verbose_name_plural': 'Authenticity Scores',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Provider'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('request_data', models.JSONField(help_text='Data sent to provider')),
                ('response_data', models.JSONField(blank=True, help_text='Response from provider', null=True)),
                ('is_authentic', models.BooleanField(blank=True, help_text='Verification result: True=authentic, False=not authentic, None=pending', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score 0-1 from provider', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='core.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.verificationprovider')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
