# Generated by Django 5.1.15 on 2026-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_phase4_authenticity_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device_identifier_type',
            field=models.CharField(blank=True, choices=[('imei', 'IMEI (Mobile phones, tablets with cellular)'), ('mac', 'MAC Address (Wi-Fi devices, laptops)'), ('serial', 'Serial Number (Laptops, consumer electronics)'), ('meid', 'MEID (CDMA devices)'), ('esn', 'ESN (Older CDMA devices)'), ('device_id', 'Device ID (Manufacturer specific)'), ('none', 'Not Applicable')], help_text='For electronic products: select the type of unique identifier.', max_length=20, null=True, verbose_name='Device Identifier Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_identifier_value',
            field=models.CharField(blank=True, help_text='Enter the unique identifier number for verification.', max_length=100, null=True, verbose_name='Device Identifier Value'),
        ),
    ]
