# Generated by Django 5.1.15 on 2026-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_product_device_identifier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_lot_number',
            field=models.CharField(blank=True, help_text='Production batch number for tracking and counterfeiting prevention.', max_length=100, null=True, verbose_name='Batch/Lot Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='certification_numbers',
            field=models.CharField(blank=True, help_text='Regulatory certifications (e.g., FCC, CE, RoHS). Comma-separated.', max_length=500, null=True, verbose_name='Certification Numbers'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, help_text='Date when the product was manufactured. Helps verify origin authenticity.', null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text="Manufacturer's model number for the product.", max_length=100, null=True, verbose_name='Model Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_service_code',
            field=models.CharField(blank=True, help_text='Code that can be verified with manufacturer for warranty and authenticity.', max_length=100, null=True, verbose_name='Warranty/Service Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_identifier_type',
            field=models.CharField(blank=True, choices=[('imei', 'IMEI (Mobile phones, tablets with cellular)'), ('mac', 'MAC Address (Wi-Fi devices, laptops)'), ('serial', 'Serial Number (Laptops, consumer electronics)'), ('meid', 'MEID (CDMA devices)'), ('esn', 'ESN (Older CDMA devices)'), ('device_id', 'Device ID (Manufacturer specific)'), ('upc', 'UPC/EAN Barcode (Universal Product Code)'), ('batch', 'Batch/Lot Number (Production batch tracking)'), ('model', 'Model Number (Product model identifier)'), ('none', 'Not Applicable')], help_text='For electronic products: select the type of unique identifier.', max_length=20, null=True, verbose_name='Device Identifier Type'),
        ),
    ]
