# Generated by Django 5.1.15 on 2026-01-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_product_batch_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergen_information',
            field=models.CharField(blank=True, help_text='Contains/may contain allergens. Comma-separated list.', max_length=500, null=True, verbose_name='Allergen Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_edition',
            field=models.CharField(blank=True, help_text='Edition information (e.g., First Edition, 2nd Edition).', max_length=100, null=True, verbose_name='Book Edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_authentication_code',
            field=models.CharField(blank=True, help_text='Code for verifying authentic brand merchandise.', max_length=100, null=True, verbose_name='Brand Authentication Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_label_instructions',
            field=models.CharField(blank=True, help_text="Washing and care instructions (e.g., 'Machine wash cold', 'Dry clean only').", max_length=500, null=True, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiration or best before date for food/beverage products.', null=True, verbose_name='Expiry/Best Before Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, help_text='International Standard Book Number for book identification.', max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_composition',
            field=models.CharField(blank=True, help_text="Material composition percentage (e.g., '100% Cotton', '80% Polyester, 20% Spandex').", max_length=500, null=True, verbose_name='Material Composition'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_date',
            field=models.DateField(blank=True, help_text='Date when the book was printed.', null=True, verbose_name='Print Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher_name',
            field=models.CharField(blank=True, help_text='Name of the book publisher for verification.', max_length=255, null=True, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.CharField(blank=True, help_text='Size variant (e.g., XL, 42, M, etc.).', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instructions',
            field=models.CharField(blank=True, help_text="How to store the product (e.g., 'Keep refrigerated', 'Store in cool dry place').", max_length=500, null=True, verbose_name='Storage Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_ean_barcode',
            field=models.CharField(blank=True, help_text='Universal Product Code or European Article Number for product identification.', max_length=20, null=True, verbose_name='UPC/EAN Barcode'),
        ),
    ]
