# Generated by Django 5.1.15 on 2026-02-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_product_allergen_information_product_book_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(help_text='Detailed description of the service offered.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Detailed description of the service offered.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(help_text='Detailed description of the service offered.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_pt',
            field=models.TextField(help_text='Detailed description of the service offered.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_zh_hans',
            field=models.TextField(help_text='Detailed description of the service offered.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_pt',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_zh_hans',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_es',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_zh_hans',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description_ar',
            field=models.TextField(help_text="Describe what's included in this package.", null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description_en',
            field=models.TextField(help_text="Describe what's included in this package.", null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description_es',
            field=models.TextField(help_text="Describe what's included in this package.", null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description_pt',
            field=models.TextField(help_text="Describe what's included in this package.", null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description_zh_hans',
            field=models.TextField(help_text="Describe what's included in this package.", null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name_ar',
            field=models.CharField(help_text="Give this package a descriptive name (e.g., 'Basic Logo', 'Full Website Setup', 'Hourly Consultation').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name_en',
            field=models.CharField(help_text="Give this package a descriptive name (e.g., 'Basic Logo', 'Full Website Setup', 'Hourly Consultation').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name_es',
            field=models.CharField(help_text="Give this package a descriptive name (e.g., 'Basic Logo', 'Full Website Setup', 'Hourly Consultation').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name_pt',
            field=models.CharField(help_text="Give this package a descriptive name (e.g., 'Basic Logo', 'Full Website Setup', 'Hourly Consultation').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name_zh_hans',
            field=models.CharField(help_text="Give this package a descriptive name (e.g., 'Basic Logo', 'Full Website Setup', 'Hourly Consultation').", max_length=100, null=True),
        ),
    ]
