# Generated by Django 5.1.15 on 2026-02-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_es',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_zh_hans',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
