# Generated by Django 5.1.15 on 2026-02-03 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_unique_on_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand name of the product.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Key features (one per line, up to 5).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.FileField(blank=True, help_text='Upload certifications for origin or quality.', null=True, upload_to='products/certifications/'),
        ),
        migrations.AddField(
            model_name='product',
            name='compliance_documents',
            field=models.FileField(blank=True, help_text='Upload compliance or legal documents.', null=True, upload_to='products/compliance/'),
        ),
        migrations.AddField(
            model_name='product',
            name='handmade_or_massproduced',
            field=models.CharField(blank=True, choices=[('handmade', 'Handmade'), ('massproduced', 'Mass-produced')], help_text='Is the product handmade or mass-produced?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_dimensions',
            field=models.CharField(blank=True, help_text='Item dimensions (e.g., 10x20x30 cm).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_weight',
            field=models.CharField(blank=True, help_text='Item weight (e.g., 1kg, 2 lbs).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='made_in_label',
            field=models.CharField(blank=True, help_text='Label to display as "Made in ...".', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_address',
            field=models.CharField(blank=True, help_text='Full address of the manufacturer.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, help_text='Manufacturer part number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_process',
            field=models.TextField(blank=True, help_text='Describe the manufacturing process (optional).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_city',
            field=models.CharField(blank=True, help_text='City or region of origin.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used_like_new', 'Used - Like New'), ('used_very_good', 'Used - Very Good'), ('used_good', 'Used - Good'), ('used_acceptable', 'Used - Acceptable'), ('collectible', 'Collectible')], default='new', help_text='Product condition (new, refurbished, used, etc.).', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='proof_of_origin',
            field=models.FileField(blank=True, help_text='Upload document or image as proof of origin.', null=True, upload_to='products/proof_of_origin/'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_warnings',
            field=models.TextField(blank=True, help_text='Safety warnings (required if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_options',
            field=models.CharField(blank=True, help_text='Shipping options (e.g., Standard, Express, International).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit (SKU) for inventory management.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability',
            field=models.CharField(blank=True, help_text='Sustainability or ethical sourcing details.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_options',
            field=models.CharField(blank=True, help_text='Variation options (comma-separated, e.g., Red, Blue, Green).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_theme',
            field=models.CharField(blank=True, help_text='Variation theme (e.g., Size, Color, Style).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(default='GOWBUY Rewards', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Platform (Gowbuy) Delivery Fee Component'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fulfillment_method',
            field=models.CharField(choices=[('gowbuy', 'Fulfilled by Gowbuy'), ('vendor', 'Fulfilled by Vendor')], default='vendor', max_length=10, verbose_name='Fulfillment Method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fulfillment_method',
            field=models.CharField(blank=True, choices=[('gowbuy', 'Fulfilled by Gowbuy'), ('vendor', 'Fulfilled by Vendor')], help_text="Leave blank to use vendor's default setting.", max_length=10, null=True, verbose_name='Product Fulfillment Method'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_es',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_zh_hans',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='GOWBUY Marketplace', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_fulfillment_method',
            field=models.CharField(choices=[('gowbuy', 'Fulfilled by Gowbuy'), ('vendor', 'Fulfilled by Vendor')], default='vendor', max_length=10, verbose_name='Default Fulfillment Method'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this vendor been verified by GOWBUY staff (e.g., identity checked)?'),
        ),
    ]
