# Generated by Django 5.1.15 on 2026-02-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_product_brand_product_bullet_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acquisition_details',
            field=models.TextField(blank=True, help_text='Provide more details about how you acquired this product (especially for items > $500).', null=True, verbose_name='Acquisition Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('i_created', 'I made/created this'), ('purchased_new', 'Purchased new from manufacturer'), ('purchased_used', 'Purchased used/secondhand'), ('consignment', 'On consignment from creator'), ('estate_auction', 'Estate sale/auction'), ('inherited_gift', 'Inherited/gifted'), ('verified_supplier', 'Sourced from verified supplier'), ('other', 'Other (explain)')], help_text='For handmade items: Where did you acquire or source this product?', max_length=50, null=True, verbose_name='Acquisition Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='artisan_product_type',
            field=models.CharField(choices=[('manufactured', 'Manufactured/Branded'), ('handmade', 'Handmade/Artisan')], default='manufactured', help_text='Is this a manufactured/branded product or handmade/artisan item?', max_length=20, verbose_name='Product Type'),
        ),
    ]
