# Generated by Django 5.1.15 on 2026-02-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_product_acquisition_details_product_acquisition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for vendor products.'),
        ),
    ]
