# Generated by Django 5.1.15 on 2026-02-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_promotion_backend_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotioncampaign',
            new_name='core_promot_vendor__b2379a_idx',
            old_name='core_promot_vendor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='promotioncampaign',
            new_name='core_promot_start_d_f4bc51_idx',
            old_name='core_promot_date_range_idx',
        ),
        migrations.RenameIndex(
            model_name='promotioncode',
            new_name='core_promot_promoti_f7cc7e_idx',
            old_name='core_promot_promot_idx',
        ),
        migrations.RenameIndex(
            model_name='promotioncode',
            new_name='core_promot_code_5482b3_idx',
            old_name='core_promot_code_idx',
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='archived',
            field=models.BooleanField(default=False, help_text='Is the campaign archived?'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Total clicks.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Conversion rate percentage (cached).', max_digits=5),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='conversions',
            field=models.PositiveIntegerField(default=0, help_text='Total conversions.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Click-through rate percentage (cached).', max_digits=5),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', help_text='Campaign health status.', max_length=20),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='impressions',
            field=models.PositiveIntegerField(default=0, help_text='Total impressions.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time metrics were updated.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='paused',
            field=models.BooleanField(default=False, help_text='Is the campaign paused by vendor?'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='performance_score',
            field=models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Average'), ('D', 'D - Poor'), ('F', 'F - Critical')], default='C', help_text='Performance grade A-F.', max_length=1),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Return on investment percentage (cached).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount spent so far.', max_digits=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
