# Generated by Django 5.1.15 on 2026-02-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_rename_core_promot_vendor_status_idx_core_promot_vendor__b2379a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Black Friday 2024').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the template.')),
                ('template_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('product_launch', 'Product Launch'), ('holiday', 'Holiday'), ('clearance', 'Clearance'), ('custom', 'Custom')], default='custom', help_text='Type of template for categorization.', max_length=20)),
                ('placement', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('search_results_top', 'Search Results (Top)'), ('category_sidebar', 'Category Sidebar')], help_text='Default placement for campaigns from this template.', max_length=50)),
                ('budget_template', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested budget for campaigns from this template.', max_digits=10, null=True)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Default campaign duration in days.')),
                ('email_enabled', models.BooleanField(default=False, help_text='Include email channel.')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Include SMS channel.')),
                ('social_enabled', models.BooleanField(default=False, help_text='Include social media channel.')),
                ('is_public', models.BooleanField(default=False, help_text='Is this template visible to other vendors? (Premium feature)')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Track how many times this template was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(help_text='The vendor who owns this template.', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Campaign Template',
                'verbose_name_plural': 'Campaign Templates',
                'ordering': ('-created_at',),
            },
        ),
    ]
