# Generated by Django 5.1.15 on 2026-02-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_campaigntemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='audience_age_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum target age.', null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='audience_age_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum target age.', null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='audience_device',
            field=models.CharField(choices=[('all', 'All Devices'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], default='all', help_text='Target device type.', max_length=20),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='audience_interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests for targeting.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='audience_location',
            field=models.CharField(blank=True, help_text='Target location (city, region, or country).', max_length=255),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='base_cta',
            field=models.CharField(blank=True, help_text='Call-to-action text.', max_length=60),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='base_description',
            field=models.CharField(blank=True, help_text='Primary description for the ad.', max_length=200),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='base_headline',
            field=models.CharField(blank=True, help_text='Primary headline for the ad.', max_length=120),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='base_image_url',
            field=models.URLField(blank=True, help_text='Image URL for the ad.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='creative_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Creative variants for A/B testing.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Include email channel.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('ctr', 'CTR %'), ('clicks', 'Clicks'), ('conversions', 'Conversions'), ('roi', 'ROI %')], help_text='Primary performance goal.', max_length=20),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='goal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target value for the goal.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list, help_text='List of days to run the campaign.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='schedule_end_time',
            field=models.TimeField(blank=True, help_text='Daily end time for campaign display.', null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='schedule_start_time',
            field=models.TimeField(blank=True, help_text='Daily start time for campaign display.', null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Include SMS channel.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='social_enabled',
            field=models.BooleanField(default=False, help_text='Include social media channel.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this campaign (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.campaigntemplate'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
