# Generated by Django 5.1.15 on 2026-02-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_adcampaign_audience_age_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Tag',
                'verbose_name_plural': 'Conversation Tags',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='auto_tags',
            field=models.TextField(blank=True, help_text='Comma-separated auto-detected tags'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(blank=True, choices=[('inquiry', 'Inquiry'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('support', 'Support'), ('order_related', 'Order Related'), ('return', 'Return'), ('other', 'Other')], default='inquiry', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_segment',
            field=models.CharField(blank=True, choices=[('vip', 'VIP'), ('repeat_buyer', 'Repeat Buyer'), ('high_value', 'High Value'), ('new_customer', 'New Customer'), ('at_risk', 'At Risk'), ('regular', 'Regular')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='first_response_time',
            field=models.DateTimeField(blank=True, help_text='Time of first response by vendor', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled follow-up reminder', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='response_time_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds until first response', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('frustrated', 'Frustrated')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('awaiting_response', 'Awaiting Response'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='urgency_score',
            field=models.IntegerField(default=5, help_text='1-10 scale: 1=low, 10=critical'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='core.conversationtag'),
        ),
    ]
