# Generated by Django 5.2 on 2025-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_customuser_facebook_url_customuser_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_service_provider',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an active service provider.', verbose_name='Is Service Provider'),
        ),
    ]
