# Generated by Django 5.2 on 2025-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_customuser_is_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Emails must be unique.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
